#!/bin/bash

# Verifica si hay contenedores activos del compose
if [ "$(sudo docker compose ps -q)" ]; then
    echo "🛑 Deteniendo contenedores existentes..."
    sudo docker compose down -v
else
    echo "✅ No hay contenedores activos"
fi

# Limpia la terminal
clear

# Levanta los contenedores
sudo docker compose up --build
